# Generated by Django 5.1.3 on 2025-03-17 15:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default=accounts.models.get_default_uuid, max_length=200),
        ),
    ]
