# Generated by Django 5.1.3 on 2025-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0012_alter_customer_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='brand_color',
            field=models.CharField(blank=True, help_text='Hex color code, e.g. #f7c028', max_length=7, null=True),
        ),
    ]
