# Generated by Django 5.1.3 on 2025-02-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0013_restaurant_brand_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='brand_color',
        ),
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Hex color code, e.g. #f7c028', max_length=7)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_colors', to='menu_dashboard.restaurant')),
            ],
        ),
    ]
