# Generated by Django 5.1.3 on 2025-02-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0014_remove_restaurant_brand_color_brandcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
