# Generated by Django 5.1.3 on 2025-02-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0015_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu_dashboard.category'),
        ),
    ]
