# Generated by Django 5.1.3 on 2025-02-24 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0017_rename_category_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='menu_dashbo_restaur_256584_idx',
            old_name='menu_dashbo_restaur_5e739c_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='category_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu_dashboard.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
