# Generated by Django 5.1.3 on 2025-02-26 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0019_rename_menu_dashbo_restaur_256584_idx_menu_dashbo_restaur_5e739c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g., 'Shot', 'Bottle', 'Small', 'Large'", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default variation?')),
                ('has_promo', models.BooleanField(default=False)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='menu_dashboard.product')),
            ],
            options={
                'ordering': ['product', '-is_default', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
