# Generated by Django 5.1.3 on 2025-02-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0020_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variations',
            field=models.BooleanField(default=False),
        ),
    ]
