# Generated by Django 5.1.3 on 2025-02-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0021_product_has_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hashed_slug',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
