# Generated by Django 5.1.3 on 2025-02-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0022_restaurant_hashed_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hashed_slug',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
