# Generated by Django 5.1.3 on 2025-02-28 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0024_menuvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuvisit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_visits', to='menu_dashboard.restaurant'),
        ),
    ]
