# Generated by Django 5.1.3 on 2025-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0025_alter_menuvisit_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuvisit',
            name='device_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
