# Generated by Django 5.1.3 on 2025-03-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0026_menuvisit_device_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuvisit',
            old_name='device_family',
            new_name='device',
        ),
    ]
