# Generated by Django 5.1.3 on 2025-03-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0027_rename_device_family_menuvisit_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('notification_type', models.CharField(choices=[('success', 'Success'), ('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
