# Generated by Django 5.1.3 on 2025-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0028_notification_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If checked, notification will be shown to all restaurants'),
        ),
        migrations.AddField(
            model_name='notification',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='menu_dashboard.restaurant'),
        ),
    ]
