# Generated by Django 5.1.3 on 2025-03-17 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0028_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('success', 'Success'), ('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
