# Generated by Django 5.1.3 on 2025-03-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0029_notification_is_global_notification_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='restaurants',
        ),
    ]
