# Generated by Django 5.1.3 on 2025-03-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0030_remove_notification_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='restaurants',
            field=models.ManyToManyField(blank=True, help_text='Select specific restaurants to receive this notification. Leave empty to send to all restaurants.', related_name='notifications', to='menu_dashboard.restaurant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_all',
            field=models.BooleanField(default=False, help_text='If checked, this notification will be sent to all restaurants regardless of selection.'),
        ),
    ]
