# Generated by Django 5.1.3 on 2025-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0031_notification_restaurants_notification_send_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='name',
            field=models.CharField(help_text="E.g., 'S', 'M', 'L', 'F", max_length=50),
        ),
    ]
