# Generated by Django 5.1.3 on 2025-03-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0032_alter_productvariation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set a percentage discount, e.g., 50 for 50% off', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.CharField(blank=True, help_text="E.g., 'Limited Time Offer!' or '50% off on Wednesdays'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set a percentage discount, e.g., 50 for 50% off', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
