# Generated by Django 5.1.3 on 2025-03-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0033_product_discount_percentage_product_special_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='charge_gst',
            field=models.BooleanField(default=True),
        ),
    ]
