# Generated by Django 5.1.3 on 2025-03-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0034_restaurant_charge_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='charge_gst',
            field=models.BooleanField(default=False),
        ),
    ]
