# Generated by Django 5.1.3 on 2025-03-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0035_alter_restaurant_charge_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_by_percentage',
            field=models.BooleanField(default=False, help_text='If checked, the discount_percentage field is used as the product price, displayed as a percentage.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If using fixed pricing, this field applies a discount; if using percentage pricing, this value is used as the displayed percentage', max_digits=5, null=True),
        ),
    ]
