# Generated by Django 5.1.3 on 2025-03-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0036_product_price_by_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="For fixed pricing, this is the discount rate applied to the price. If using percentage pricing, this value is shown as the price (with a '%' sign).", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_by_percentage',
            field=models.BooleanField(default=False, help_text="If enabled, the product will display its price as a percentage (e.g., '50%') instead of a fixed amount."),
        ),
    ]
