# Generated by Django 5.1.3 on 2025-03-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0037_alter_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='charge_gst',
            field=models.BooleanField(default=True),
        ),
    ]
