# Generated by Django 5.1.3 on 2025-04-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0038_alter_restaurant_charge_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='charge_gst',
        ),
        migrations.AddField(
            model_name='product',
            name='charge_gst',
            field=models.BooleanField(default=True, help_text='If True, 10% GST will be added.'),
        ),
    ]
