# Generated by Django 5.1.3 on 2025-04-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0039_remove_restaurant_charge_gst_product_charge_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='charge_gst',
            field=models.BooleanField(default=False, help_text='If True, 10% GST will be added.'),
        ),
    ]
