# Generated by Django 5.1.3 on 2025-04-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0040_alter_product_charge_gst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
