# Generated by Django 5.1.3 on 2025-04-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0041_add_restaurant_slug'),
        ('menu_dashboard', '0041_delete_delivery'),
    ]

    operations = [
    ]
