# Generated by Django 5.1.3 on 2025-04-05 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0042_merge_0041_add_restaurant_slug_0041_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered', models.BooleanField(db_index=True, default=False)),
                ('delivery_feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu_dashboard.deliveryrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery_request', 'delivered'], name='menu_dashbo_deliver_8cc99d_idx')],
            },
        ),
    ]
