# Generated by Django 5.1.3 on 2025-04-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0043_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
