# Generated by Django 5.1.3 on 2025-04-05 02:12




from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('menu_dashboard', '0044_alter_restaurant_slug'),  # Replace with your previous migration
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "menu_dashboard_deliveryrequest" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "status" varchar(50) NOT NULL,
                "request_time" datetime NOT NULL,
                "order_id" integer NOT NULL UNIQUE REFERENCES "menu_dashboard_orders" ("id") DEFERRABLE INITIALLY DEFERRED,
                "rider_id" integer NULL REFERENCES "menu_dashboard_rider" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX IF NOT EXISTS "menu_dashboard_deliveryrequest_order_id_rider_id_status_idx" ON "menu_dashboard_deliveryrequest" ("order_id", "rider_id", "status");
            CREATE INDEX IF NOT EXISTS "menu_dashboard_deliveryrequest_status_df82eb6e" ON "menu_dashboard_deliveryrequest" ("status");
            CREATE INDEX IF NOT EXISTS "menu_dashboard_deliveryrequest_request_time_fd3d3e75" ON "menu_dashboard_deliveryrequest" ("request_time");
            """
        ),
    ]