# Generated by Django 5.1.3 on 2025-04-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0045_auto_20250404_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='charge_gst',
            field=models.BooleanField(default=False, help_text='If True, 12% GST will be added.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For fixed pricing, this is the discount rate applied to the price.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_by_percentage',
            field=models.BooleanField(default=False, help_text="If enabled, the product will display its price as a percentage (e.g., '50%')."),
        ),
    ]
