# Generated by Django 5.1.3 on 2025-04-09 20:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0046_alter_product_charge_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo_pic'),
        ),
    ]
