# Generated by Django 5.1.3 on 2025-04-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0048_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='logo_pic/RestaurantLogo/'),
        ),
    ]
