# Generated by Django 5.1.3 on 2025-04-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0049_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_mode',
            field=models.CharField(choices=[('dinein', 'Dine-in'), ('delivery', 'Delivery')], default='dinein', max_length=20),
        ),
    ]
