# Generated by Django 5.1.3 on 2025-04-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0050_orders_delivery_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_mode',
        ),
    ]
