# Generated by Django 5.1.3 on 2025-04-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_dashboard', '0051_remove_orders_delivery_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='±DDD.DDDDDDDD (3 digits integer, 8 digits fractional)', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='±DDD.DDDDDDDD (3 digits integer, 8 digits fractional)', max_digits=11, null=True),
        ),
    ]
